### PR TITLE
Add rubies 2.6, 2.7, and 3.0 to test in Travis CI

### PR DESCRIPTION
**Pull request by etagwerker**
Hey, 

This PR adds configuration to test the library with Ruby 2.6, 2.7, and 3.0. Pretty straightforward. 😄 

Please check it out and let me know what you think.

Thanks!

### CODE REVIEW

**Comment by jmmastey** [comment]
Hey @etagwerker, love y'all's work at @fastruby.

This PR looks perfectly lovely, happy to merge it. That said, as you can see, this project has been pretty stable for a while, so I'm not sure if it's buying much at the moment.

**Comment by etagwerker** [comment]
@jmmastey Hey, thanks for your kind words! 😊 

I submitted this contribution because I wanted to make sure that `bundler-stats` worked with the latest rubies out there. I'm working on a contribution for `rails_stats` that would add a dependency on `bundler-stats` (https://github.com/fastruby/rails_stats/pull/21) 

I noticed an issue in the GitHub Actions CI jobs. Later I realized that it is not an issue with `bundler-stats` but with the "terminal" that CI is trying to use...

**Comment by jmmastey** [comment]
Going to go ahead and merge this, thanks for the contribution!

**Comment by jmmastey** [comment]
I'll wait until the other PR is done before I cut a new version

**Pull request merged**
