### PR TITLE
Feature/output with predictable sorting

### LINKED ISSUE #20: [BUG] Different order in results table for different environment
Hi there, 

I've noticed a weird issue when adding a feature to `rails_stats` which relies on `bundler-stats`, the order of the gems has one order in my MacBook Pro and a slightly different order in GitHub CI. 

```
  1) Failure: RailsStats::CodeStatistics::#to_s#test_0001_outputs useful stats for a Rails project [/home/runner/work/rails_stats/rails_stats/test/lib/rails_stats/code_statistics_test.rb:48]:
--- expected
+++ actual
@@ -6,10 +6,10 @@
 |           rails_stats | 4          | 2              |
 |             simplecov | 3          | 3              |
 |       minitest-around | 1          | 1              |
+| minitest-spec-context | 0          | 0              |
 |              minitest | 0          | 0              |
-|               bundler | 0          | 0              |
 |                byebug | 0          | 0              |
-| minitest-spec-context | 0          | 0              |
+|               bundler | 0          | 0              |
 +-----------------------|------------|----------------+
                           
       Declared Gems   9   

2 runs, 10 assertions, 1 failures, 0 errors, 0 skips
Coverage report generated for Unit Tests to /home/runner/work/rails_stats/rails_stats/coverage. 487 / 670 LOC (72.69%) covered.
```

Source: https://github.com/fastruby/rails_stats/pull/21

I think this could be fixed if `gem_stats` returned a result that was sorted by two attributes:

- Total Dependencies (descending)
- Name (ascending) 

The patch should be pretty straightforward. If you are interested I could submit a PR for this.

### PR DESCRIPTION
**Pull request by etagwerker**
Hey @jmmastey,

This PR fixes #20 in a pretty straightforward way. 

Please let me know what you think.

Thanks!

### CODE REVIEW

**Comment by jmmastey** [comment]
Hello again! Dig the feature; makes sense. Implementation seems just fine.

Can we talk about how long that new test is? 😆  Would you be willing to pare that down to just a few lines that illustrate the sort? Then we can merge this and I think cut the new version for y'all.

**Comment by etagwerker** [comment]
@jmmastey sure thing. I guess it is good enough to check with `end_with` and simply use the last part. I initially found this bug a little annoying because the gems with 0 dependencies were not alphabetically sorted. 

I just updated it to simply check the tail of the array. Is that what you had in mind?

**Comment by jmmastey** [comment]
Seems closer, but that stops testing the lexical sort. Sorry, thinking through what would actually be a solid test here. Given there's another test that at least covers the basics of the method, what about something like this:

```ruby
allow(target.gemfile).to receive(:map).and_return([
  { total_dependencies: 0, name: 'DDD' },
  { total_dependencies: 0, name: 'CCC' },
  { total_dependencies: 9, name: 'BBB' },
  { total_dependencies: 9, name: 'AAA' },
])

resp = calculator.gem_stats

expect(resp.map { |h| h[:name] }).to eq([
  'AAA', 'BBB', 'CCC', 'DDD',
])
```

Something to exercise the sort itself, but hopefully in a simplified way. Feels more abstract than your existing test, but looking back at the example lockfile, I don't see another elegant way to test the order.

**Comment by etagwerker** [comment]
> Seems closer, but that stops testing the lexical sort.

@jmmastey `end_with` does test for the lexical sort. I just pushed https://github.com/jmmastey/bundler-stats/pull/21/commits/b0a8016b0cd38ae0cb92dfcdada1e761622318f9 to show that the scenario fails if the array is not sorted properly...

**Comment by jmmastey** [comment]
This looks great. Thanks for the revisions.

**Comment by jmmastey** [comment]
@etagwerker okay, released 2.1.0 w/ all your changes! may release a quick 2.1.1 w/ some cleanup based on changes to `gem build` since the last time this gem was released, but I don't expect that to affect running the gem at all.

thanks again for the contributions!

**Comment by etagwerker** [comment]
@jmmastey awesome, thank you!

**Pull request merged**
