### PR TITLE
Fixes/argument error integer tput

### LINKED ISSUE #18: [BUG] ArgumentError within GitHub CI environment: invalid value for Integer(): ""
Hi @jmmastey,

Thanks for creating this gem! It has been very useful in estimating how big a Ruby/Rails application really is. I wrote a little bit about it over here: [How we estimate the size of a Rails application](https://www.fastruby.io/blog/rails/code-quality/how-we-estimate-rails-application-size.html#total-dependencies)

I wanted to incorporate it to `rails_stats` as a way to get both bundler and LOC stats, so I went ahead and submitted: https://github.com/fastruby/rails_stats/pull/21

Unfortunately my test suite fails with this error: 

```
  1) Error:
50
RailsStats::CodeStatistics::#to_s#test_0001_outputs useful stats for a Rails project:
51
ArgumentError: invalid value for Integer(): ""
52
    /home/runner/work/rails_stats/rails_stats/vendor/bundle/ruby/2.4.0/gems/bundler-stats-2.0.1/lib/bundler/stats/printer.rb:40:in `Integer'
53
    /home/runner/work/rails_stats/rails_stats/vendor/bundle/ruby/2.4.0/gems/bundler-stats-2.0.1/lib/bundler/stats/printer.rb:40:in `terminal_width'
54
    /home/runner/work/rails_stats/rails_stats/vendor/bundle/ruby/2.4.0/gems/bundler-stats-2.0.1/lib/bundler/stats/printer.rb:50:in `column_widths'
55
    /home/runner/work/rails_stats/rails_stats/vendor/bundle/ruby/2.4.0/gems/bundler-stats-2.0.1/lib/bundler/stats/printer.rb:21:in `to_s'
56
    /home/runner/work/rails_stats/rails_stats/vendor/bundle/ruby/2.4.0/gems/bundler-stats-2.0.1/lib/bundler/stats/cli.rb:69:in `draw_stats'
57
    /home/runner/work/rails_stats/rails_stats/vendor/bundle/ruby/2.4.0/gems/bundler-stats-2.0.1/lib/bundler/stats/cli.rb:23:in `stats'
58
    /home/runner/work/rails_stats/rails_stats/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
59
    /home/runner/work/rails_stats/rails_stats/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
60
    /home/runner/work/rails_stats/rails_stats/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
61
    /home/runner/work/rails_stats/rails_stats/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
62
    /home/runner/work/rails_stats/rails_stats/lib/rails_stats/console_formatter.rb:6:in `to_s'
63
    /home/runner/work/rails_stats/rails_stats/lib/rails_stats/code_statistics.rb:11:in `to_s'
64
    /home/runner/work/rails_stats/rails_stats/test/lib/rails_stats/code_statistics_test.rb:45:in `block (4 levels) in <top (required)>'
65
```

I see that in your test suite you stub the method that calls `tput`: https://github.com/jmmastey/bundler-stats/blob/b55fd315c8c4ff10076a377b452bccbca780b1c6/spec/lib/bundler/stats/printer_spec.rb#L7-L9 

I assume that is a good way to get around that issue in CI. 

Would you be interested in a simple patch to [this method](https://github.com/jmmastey/bundler-stats/blob/b55fd315c8c4ff10076a377b452bccbca780b1c6/lib/bundler/stats/printer.rb#L39-L43)?

Please let me know.

Thanks,
Ernesto

### PR DESCRIPTION
**Pull request by etagwerker**
Hey @jmmastey, 

This PR fixes #18. 

Please check it out and let me know what you think. 

Thanks!

### CODE REVIEW

**Comment by jmmastey** [comment]
I like the overall shape of the solution, but the use of `ArgumentError` feels a little funky. Looks like it's also possible for `Integer(str)` to raise TypeError. And then rescuing both separately feels potentially even weirder.

Curious on your opinion on two ideas:

Possibility one, just Pokemon rescue all `StandardError`s and be done with it. I don't recall writing that method, but I don't see a lot of value to letting any errors out of that method.

Or two, use `Integer(str, exception: false) || 80`. Feels a little duplicative of the other 80, but only guards against errors of casting into integers.

**Comment by etagwerker** [comment]
@jmmastey Thanks for the quick response! ❤️ 

> Possibility one, just Pokemon rescue all StandardErrors and be done with it. I don't recall writing that method, but I don't see a lot of value to letting any errors out of that method.

I like this idea. If the user sees unexpected behavior (related to their terminal width) at least they will see something like "tput: No value for $TERM and no -T specified" in their stdout. 

> Or two, use Integer(str, exception: false) || 80. Feels a little duplicative of the other 80, but only guards against errors of casting into integers.

This would be great if it were available since before Ruby 2.6, but it is not. Selfishly speaking here (😄) because I work with projects that are sometimes running Ruby 2.3 or older, I would prefer not to implement it with this idiom...

**Comment by etagwerker** [comment]
@jmmastey I just pushed the adjustment to the rescue parameters. Please let me know if you have any other comments. Thanks!

**Comment by jmmastey** [comment]
I definitely like keeping the dependencies as wide open as possible, for the same reason it's helpful to y'all. Looks good to me, thanks again.

**Pull request merged**
